import React from 'react';
//import pics
import andy from '../images/andy.png';
import alan from '../images/alan.png';
import damien from '../images/damien.png';
import dafyd from '../images/dafyd.png';
import franny from '../images/franny.png';
import gary from '../images/gary.png';
import geoff from '../images/geoff.png';
import graeme from '../images/graeme.png';
import jerry from '../images/jerry.png';
import kev from '../images/kev.png';
import nigel from '../images/nigel.png';
import ron from '../images/ron.png';
import rupert from '../images/rupert.png';
import norman from '../images/norman.png';
import micky from '../images/micky.png';
import peter from '../images/peter.png';
import philip from '../images/philip.png';
import gordon from '../images/gordon.png';
import harry from '../images/harry.png';
import rodney from '../images/rodney.png';
import bobby from '../images/bobby.png';
import stuart from '../images/stuart.png';
import fergus from '../images/fergus.png';
import jim from '../images/jim.png';

export const Data = [
	{
		name: 'Andy',
		hair: 'blonde',
		beard: false,
		moustache: false,
		id: 1,
		perm: true,
		mullet: false,
		sidies: false,
		image: andy,
	},
	{
		name: 'Alan',
		hair: 'brown',
		beard: false,
		moustache: false,
		id: 2,
		perm: true,
		mullet: true,
		sidies: true,
		image: alan,
	},
	{
		name: 'Dafyd',
		hair: 'brown',
		beard: false,
		moustache: true,
		id: 3,
		perm: false,
		mullet: true,
		sidies: false,
		image: dafyd,
	},
	{
		name: 'Damien',
		hair: 'brown',
		beard: true,
		moustache: true,
		id: 4,
		perm: false,
		mullet: false,
		sidies: true,
		image: damien,
	},
	{
		name: 'Franny',
		hair: 'blonde',
		beard: false,
		moustache: false,
		id: 5,
		perm: true,
		mullet: false,
		sidies: true,
		image: franny,
	},
	{
		name: 'gary',
		hair: 'brown',
		beard: false,
		moustache: false,
		id: 6,
		perm: false,
		mullet: true,
		sidies: false,
		image: gary,
	},
	{
		name: 'geoff',
		hair: 'brown',
		beard: false,
		moustache: true,
		id: 7,
		perm: false,
		mullet: false,
		sidies: true,
		image: geoff,
	},
	{
		name: 'graeme',
		hair: 'brown',
		beard: false,
		moustache: false,
		id: 8,
		perm: false,
		mullet: true,
		sidies: false,
		image: graeme,
	},
	{
		name: 'jerry',
		hair: 'brown',
		balding: true,
		beard: false,
		moustache: false,
		id: 9,
		perm: false,
		mullet: false,
		sidies: true,
		image: jerry,
	},
	{
		name: 'Kev',
		hair: 'brown',
		beard: false,
		moustache: false,
		id: 10,
		perm: true,
		mullet: false,
		sidies: false,
		image: kev,
	},
	{
		name: 'nigel',
		hair: 'brown',
		beard: false,
		moustache: false,
		id: 11,
		perm: true,
		mullet: true,
		sidies: false,
		image: nigel,
	},
	{
		name: 'ron',
		hair: 'blonde',
		beard: false,
		moustache: false,
		id: 12,
		perm: false,
		mullet: false,
		sidies: true,
		image: ron,
	},
	{
		name: 'rupert',
		hair: 'brown',
		beard: false,
		moustache: true,
		id: 13,
		perm: false,
		mullet: false,
		sidies: false,
		image: rupert,
	},
	{
		name: 'norman',
		hair: 'blonde',
		beard: false,
		moustache: false,
		id: 14,
		perm: false,
		mullet: false,
		sidies: true,
		image: norman,
	},
	{
		name: 'micky',
		hair: 'blonde',
		beard: false,
		moustache: true,
		id: 15,
		perm: false,
		mullet: true,
		sidies: true,
		image: micky,
	},
	{
		name: 'peter',
		hair: 'brown',
		balding: true,
		beard: false,
		moustache: false,
		id: 16,
		perm: false,
		mullet: false,
		sidies: true,
		image: peter,
	},
	{
		name: 'philip',
		hair: 'brown',
		beard: false,
		moustache: true,
		id: 17,
		perm: true,
		mullet: false,
		sidies: false,
		image: philip,
	},
	{
		name: 'gordon',
		hair: 'blonde',
		beard: false,
		moustache: false,
		id: 18,
		perm: false,
		mullet: true,
		sidies: false,
		image: gordon,
	},
	{
		name: 'harry',
		hair: 'brown',
		beard: true,
		moustache: true,
		id: 19,
		perm: false,
		mullet: false,
		sidies: true,
		image: harry,
	},
	{
		name: 'rodney',
		hair: 'blonde',
		beard: false,
		moustache: false,
		id: 20,
		perm: false,
		mullet: true,
		sidies: true,
		image: rodney,
	},
	{
		name: 'bobby',
		hair: 'blonde',
		balding: true,
		beard: false,
		moustache: false,
		id: 21,
		perm: false,
		mullet: false,
		sidies: true,
		image: bobby,
	},
	{
		name: 'stuart',
		hair: 'brown',
		beard: false,
		moustache: true,
		id: 22,
		perm: false,
		mullet: false,
		sidies: true,
		image: stuart,
	},
	{
		name: 'fergus',
		hair: 'brown',
		beard: false,
		moustache: false,
		id: 23,
		perm: false,
		mullet: true,
		sidies: false,
		image: fergus,
	},
	{
		name: 'jim',
		hair: 'brown',
		beard: false,
		moustache: false,
		id: 24,
		perm: false,
		mullet: true,
		sidies: true,
		image: jim,
	},
];
